# Подключение к H2 с постоянным хранением в файле (в папке data внутри проекта)
spring.datasource.url=jdbc:h2:file:./data/tasktracker
spring.datasource.username=sa
spring.datasource.password=

# Настройки JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Включение консоли H2 (доступна по адресу http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console